name: CI

on: pull_request

jobs:

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Lint check
      run: npm run lint

  build:
    name: Build check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    - name: Build check with Node 14
      run: npm run build
    - name: Build check with Node 12
      run: npm install @types/node@12 -D && npm run build
    - name: Build check with Node 10
      run: npm install @types/node@10 -D && npm run build
